# Generated by Django 5.0.3 on 2024-03-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindFlow', '0002_alter_comments_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='users',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='users',
            unique_together={('email', 'username', 'password')},
        ),
    ]
