# Generated by Django 5.0.3 on 2024-03-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindFlow', '0003_alter_users_unique_together_users_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
