# Generated by Django 5.0.3 on 2024-03-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindFlow', '0005_alter_users_unique_together_users_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
